name: 🤖 AIGeT Issue Generator

on:
  push:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  run-aiget:
    runs-on: ubuntu-latest
    env:
      AIGET_GITHUB_TOKEN: ${{ secrets.AIGET_GITHUB_TOKEN }}
      REPO_NAME: "jagritiS/AIGeT"  # Set the repository name here
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: 🤖 Run AIGeT Script
        run: python aiget_main.py
